steps:

# pull the image
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
    - '-c'
    - >-
      docker pull us-central1-docker.pkg.dev/eighth-vehicle-375706/dockerbitcoin/bitcoin:latest
      || exit 0

# build the container image
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=us-central1-docker.pkg.dev/eighth-vehicle-375706/dockerbitcoin/bitcoin:latest
  - --cache=true
  - --cache-ttl=6h
  #id: Build

# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/eighth-vehicle-375706/dockerbitcoin/bitcoin:$COMMIT_SHA']

  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'dockerbitcoin', '--image', 'us-central1-docker.pkg.dev/eighth-vehicle-375706/dockerbitcoin/bitcoin', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY
